apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nitroleague-website
    app.kubernetes.io/instance: nitroleague-website
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  name: nitroleague-website
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate  
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: nitroleague-website
  template:
    metadata:
      labels:
        app: nitroleague-website
    spec:
      containers:
        - image: 168237867270.dkr.ecr.us-east-1.amazonaws.com/pre-prod-nitroleague-website:latest
          imagePullPolicy: Always
          name: nitroleague-website
          ports:
            - containerPort: 3000
