import { awsAssetsFetcher } from "../utils/awsAssetsFetcher";

export const BackersData = [
  awsAssetsFetcher("backer-01", "svg"),
  awsAssetsFetcher("backer-02"),
  awsAssetsFetcher("backer-03", "svg"),
  awsAssetsFetcher("backer-04"),
  awsAssetsFetcher("backer-05"),
  awsAssetsFetcher("backer-06"),
  awsAssetsFetcher("backer-07"),
  awsAssetsFetcher("backer-08"),
  awsAssetsFetcher("backer-09"),
  awsAssetsFetcher("backer-10"),
  awsAssetsFetcher("backer-11"),
  awsAssetsFetcher("backer-12", "svg"),
  awsAssetsFetcher("backer-13"),
  awsAssetsFetcher("backer-14", "svg"),
  awsAssetsFetcher("backer-15", "svg"),
  awsAssetsFetcher("backer-16"),
  awsAssetsFetcher("backer-17"),
  awsAssetsFetcher("backer-18"),
  awsAssetsFetcher("backer-19"),
  awsAssetsFetcher("backer-20", "svg"),
  awsAssetsFetcher("backer-21"),
  awsAssetsFetcher("backer-22", "svg"),
  awsAssetsFetcher("backer-23"),
  awsAssetsFetcher("backer-24"),
  awsAssetsFetcher("backer-25", "svg"),
  awsAssetsFetcher("backer-26"),
  awsAssetsFetcher("backer-27", "svg"),
];
