import { awsAssetsFetcher } from "utils/awsAssetsFetcher";

export const marketPlaceData = [
  {
    Image: awsAssetsFetcher("sobek-ward-m"),
    name: "Sobek Ward",
    model: "SWX-600",
    class: " sigma class",
    rarity: "Special",
    price: "$2499.99",
    href: "/sobek-ward",
  },
  {
    Image: awsAssetsFetcher("maahes-night-m"),
    name: "Maahes Night",
    model: "MNX-600",
    class: "sigma class",
    rarity: "Rare",
    price: "$499.99",
    href: "/mahees-night",
  },
  {
    Image: awsAssetsFetcher("horus-quake-m"),
    name: "Horus Quake",
    model: "HQX-600",
    class: " sigma class",
    rarity: "Common",
    price: "$99.99",
    href: "/horus-quake",
  },
  {
    Image: awsAssetsFetcher("road-ripper-m"),
    name: "Road Ripper",
    model: "RRX-600",
    class: " sigma class",
    rarity: "Uncommon",
    price: "$149.99",
    href: "/road-ripper",
  },
  {
    Image: awsAssetsFetcher("apollo-blink-m"),
    name: "Apollo Blink",
    model: "ABX-204",
    class: " Beta Class",
    rarity: "Rare",
    price: "$499.99",
    href: "/apollo-blink",
  },
  {
    Image: awsAssetsFetcher("chaos-void-m"),
    name: "Chaos Void",
    model: "CVX-104",
    class: " Alpha Class",
    rarity: "Common",
    price: "$99.99",
    href: "/chaos-void",
  },
  {
    Image: awsAssetsFetcher("aion-spirit-m"),
    name: "Aion Spirit",
    model: "ASX-104",
    class: " Alpha Class",
    rarity: "Uncommon",
    price: "$149.99",
    href: "/aion-spirit",
  },
  {
    Image: awsAssetsFetcher("bellona-eternity-m"),
    name: "Bellona Eternity",
    model: "BEX-204",
    class: "Beta Class",
    rarity: "Special",
    price: "$2499.99",
    href: "/bellona-eternity",
  },
  {
    Image: awsAssetsFetcher("polka-m"),
    name: "Chaos Void Polka Lokr",
    model: "CVX-104L",
    class: "Alpha Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/chaos-void-polka-lokr",
  },
  {
    Image: awsAssetsFetcher("quake-dafi-m"),
    name: "Horus Quake Dafi",
    model: "HQX-600D",
    class: "Sigma Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/horus-quake-dafi",
  },
  {
    Image: awsAssetsFetcher("Polinate-m"),
    name: "Horus Quake Polinate",
    model: "HQX-600P",
    class: "Sigma Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/horus-quake-polinate",
  },
  {
    Image: awsAssetsFetcher("polka-lokr-m"),
    name: "Chaos Void Polygen",
    model: "CVX-104P",
    class: "Alpha Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/chaos-void-polygen",
  },
];
