import { awsAssetsFetcher } from "utils/awsAssetsFetcher";

export const Swipper = [
  {
    featureCar: awsAssetsFetcher("aion-spirit-m"),
    name: "Aion Spirit",
    model: "ASX-104",
    class: "alpha class",
    rarity: "uncommon",
    price: "$149.99",
    href: "/aion-spirit",
  },
  {
    featureCar: awsAssetsFetcher("apollo-blink-m"),
    name: "Apollo Blink",
    model: "ABX-600",
    class: "beta class",
    rarity: "rare",
    price: "$499.99",
    href: "/apollo-blink",
  },
  {
    featureCar: awsAssetsFetcher("maahes-night-m"),
    name: "Maahes Night",
    model: "MNX-600",
    class: "sigma class",
    rarity: "rare",
    price: "$499.99",
    href: "/mahees-night",
  },
  {
    featureCar: awsAssetsFetcher("horus-quake-m"),
    name: "Horus Quake",
    model: "HQX-600",
    class: "sigma class",
    rarity: "common",
    price: "$99.99",
    href: "/horus-quake",
  },
  {
    featureCar: awsAssetsFetcher("bellona-eternity-m"),
    name: "Bellona Eternity",
    model: "BEX-204",
    class: "beta class",
    rarity: "special",
    price: "$2499.99",
    href: "/bellona-eternity",
  },
  {
    featureCar: awsAssetsFetcher("chaos-void-m"),
    name: "Chaos Void",
    model: "CVX-104",
    class: "alpha class",
    rarity: "common",
    price: "$99.99",
    href: "/chaos-void",
  },
  {
    featureCar: awsAssetsFetcher("road-ripper-m"),
    name: "Road Ripper",
    model: "RRX-600",
    class: "sigma class",
    rarity: "uncommon",
    price: "$149.99",
    href: "road-ripper",
  },
  {
    featureCar: awsAssetsFetcher("polka-m"),
    name: "Chaos Void Polka Lokr",
    model: "CVX-104L",
    class: "Alpha Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/chaos-void-polka-lokr",
  },
  {
    featureCar: awsAssetsFetcher("quake-dafi-m"),
    name: "Hours Quake Dafi",
    model: "HQX-600D",
    class: "Sigma Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/horus-quake-dafi",
  },
  {
    featureCar: awsAssetsFetcher("Polinate-m"),
    name: "Hours Quake Polinate",
    model: "HQX-600P",
    class: "Sigma Class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/horus-quake-polinate",
  },
  {
    featureCar: awsAssetsFetcher("polka-lokr-m"),
    name: "Chaos Void Polygen",
    model: "CVX-104P",
    class: "alpha class",
    rarity: "Common",
    price: "Coming Soon",
    href: "/chaos-void-polygen",
  },
];
